# =============================================================================
# fig02_reallocation.R -- "Myc reprioritises the mitochondrial compartment"
# -----------------------------------------------------------------------------
# The MAIN reallocation result, one clean point: Myc does not just RAISE the
# mitochondrial compartment (content, fig01) -- it reshuffles PRIORITY within it.
# mitoPPS (Monzel 2025) is content-blind: every MitoPathway is ratio-normalized to
# centre at 1, so a per-sample scatter is directly comparable across pathways and
# deviations from 1 are the relative priority. Reprioritisation = the pathway tiers
# shift in OPPOSITE directions with Myc -- biogenesis machinery (import, central
# dogma) promoted, dynamics/surveillance + signalling + transport demoted -- and
# it holds at BOTH ages. (OXPHOS is ~neutral at tier level; its within-tier
# subunit-vs-assembly split is the supplementary figS3.)
#
# One dot per pathway per sample, coloured by tier; bold crossbars = the per-
# genotype tier mean, so the WT -> Myc+ gap of a tier is the reallocation.
# Genotype (Myc+ vs WT within a timepoint) is the clean axis; 6W and 12W faceted
# on the same figure. DESCRIPTIVE / EXPLORATORY (n=6/group): the claim is the
# coherent pattern across both ages, not per-pathway significance.
#
# Reads (read-only; NO re-run -- regenerated by the author's post-reconciliation run):
#   results/mitopps_scores.rds -- $mitopps_scores (tidy: sample/group/timepoint/
#       myc_status + 144 pathway columns, ratio-normalized), $pathway_tier1_map.
# =============================================================================

source(here::here("figures", "theme_myc.R"))

out_dir <- here::here("outputs", "figures")

mp   <- readRDS(here::here("results", "mitopps_scores.rds"))
sc   <- mp$mitopps_scores
tier <- mp$pathway_tier1_map

meta   <- c("sample", "group", "timepoint", "myc_status")
pw_col <- setdiff(names(sc), meta)

# --- long: sample x pathway x score, with tier -------------------------------
long <- tidyr::pivot_longer(sc, dplyr::all_of(pw_col),
                            names_to = "pathway", values_to = "score")
long$tier <- unname(tier[long$pathway])
long <- long[!is.na(long$tier), ]

# --- tier order (by Myc@6W effect: promoted -> demoted) + short labels --------
tier_lv  <- c("Protein import, sorting and homeostasis",
              "Mitochondrial central dogma", "OXPHOS", "Metabolism",
              "Signaling", "Mitochondrial dynamics and surveillance",
              "Small molecule transport")
tier_lab <- c("Import / homeostasis", "Central dogma", "OXPHOS", "Metabolism",
              "Signaling", "Dynamics & surveillance", "SM transport")
names(tier_lab) <- tier_lv
# Okabe-Ito qualitative; Metabolism (67 pathways, ~neutral, dominates the cloud)
# muted to grey so the promoted/demoted tiers stand out.
tier_col <- c("Import / homeostasis"    = "#D55E00",   # promoted (warm)
              "Central dogma"           = "#E69F00",
              "OXPHOS"                  = "#009E73",   # ~neutral
              "Metabolism"              = "grey72",    # neutral bulk, receded
              "Signaling"               = "#56B4E9",
              "Dynamics & surveillance" = "#0072B2",   # demoted (cool)
              "SM transport"            = "#CC79A7")
long$tier <- factor(unname(tier_lab[long$tier]), levels = unname(tier_lab[tier_lv]))

# --- x positions: WT block (1-6) then Myc+ block (7-12) within each timepoint --
long$timepoint <- factor(long$timepoint, levels = c("6W", "12W"),
                         labels = c("6 weeks", "12 weeks"))
xpos_of <- function(d) {
  s <- unique(d[, c("sample", "myc_status")])
  s <- s[order(s$myc_status != "neg", s$sample), ]   # neg first
  stats::setNames(seq_len(nrow(s)), s$sample)
}
xmap <- tapply(seq_len(nrow(long)), long$timepoint, function(i) xpos_of(long[i, ]))
long$xpos <- mapply(function(tp, sm) xmap[[as.character(tp)]][[sm]],
                    long$timepoint, long$sample)

# --- tier-mean crossbars per timepoint x genotype x tier ----------------------
bars <- long |>
  dplyr::group_by(timepoint, myc_status, tier) |>
  dplyr::summarise(m = mean(score),
                   x0 = min(xpos) - 0.45, x1 = max(xpos) + 0.45, .groups = "drop")

NCAP <- c(0.6, 1.5)   # display window (a handful of pathways sit outside; means intact)

p <- ggplot2::ggplot(long, ggplot2::aes(xpos, score, colour = tier)) +
  ggplot2::geom_hline(yintercept = 1, linetype = 2, linewidth = 0.3, colour = "grey55") +
  ggplot2::geom_vline(xintercept = 6.5, linewidth = 0.3, colour = "grey85") +
  ggplot2::geom_jitter(width = 0.34, height = 0, size = 0.35, alpha = 0.35) +
  # tier-mean crossbars (bold) -- the WT->Myc+ gap per tier is the reallocation
  ggplot2::geom_segment(data = bars, inherit.aes = FALSE,
                        ggplot2::aes(x = x0, xend = x1, y = m, yend = m, colour = tier),
                        linewidth = 1.1) +
  ggplot2::facet_wrap(~ timepoint, nrow = 1) +
  ggplot2::coord_cartesian(ylim = NCAP) +
  ggplot2::scale_colour_manual(values = tier_col, name = "MitoPathway tier") +
  ggplot2::scale_x_continuous(breaks = c(3.5, 9.5), labels = c("WT", "Myc+"),
                              expand = ggplot2::expansion(add = 0.6)) +
  ggplot2::labs(
    x = NULL, y = "mitoPPS score (relative priority; 1 = compartment average)",
    title = "Myc reprioritises the mitochondrial compartment",
    subtitle = "Biogenesis machinery (import, central dogma) up; dynamics, signalling, transport down.",
    caption = paste(
      "mitoPPS (Monzel 2025), content-blind: each MitoPathway ratio-normalized to 1. Dot = one pathway per sample; bold bar = per-genotype tier mean.",
      "Genotype is the clean axis; the pattern holds at 6W and 12W. Descriptive/exploratory (n=6/group); a few pathways sit off-scale.",
      sep = "\n")) +
  theme_myc(base_size = 9) +
  ggplot2::theme(
    axis.text.x     = ggplot2::element_text(face = "bold"),
    axis.ticks.x    = ggplot2::element_blank(),
    legend.position = "right",
    legend.key.size = ggplot2::unit(3.5, "mm"),
    panel.spacing.x = ggplot2::unit(6, "mm")) +
  ggplot2::guides(colour = ggplot2::guide_legend(
    override.aes = list(size = 2.6, alpha = 1, linetype = 0)))

# Guard: sourced only to obtain `p` (e.g. Quarto) when myc.fig.nosave = TRUE.
if (!isTRUE(getOption("myc.fig.nosave"))) {
  if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)
  save_panel(p, file.path(out_dir, "fig02_reallocation.pdf"),
             width = fig_w[["double"]], height = 105)
}

# =============================================================================
# SANDBOX -- run line-by-line in Positron; skipped by source()
# =============================================================================
if (FALSE) {
  # tier-mean reallocation (Myc - WT) at each age -- the numbers behind the bars
  w <- bars |>
    tidyr::pivot_wider(names_from = myc_status, values_from = m,
                       id_cols = c(timepoint, tier)) |>
    dplyr::mutate(d = pos - neg)
  print(as.data.frame(w[order(w$timepoint, -w$d), ]), digits = 2)
  print(p)
}
