# =============================================================================
# fig02_reallocation_two_rulers.R -- content vs mitoPPS across ALL MitoPathways
# -----------------------------------------------------------------------------
# The reallocation result. fig01/figS1/figS2 show Myc RAISES nuclear mito CONTENT
# broadly (absolute). mitoPPS (Monzel 2025) is content-BLIND -- it reads RELATIVE
# resource reallocation WITHIN the compartment. This panel confronts the two rulers
# across all ~148 MitoPathways, tier-blocked:
#   LEFT  "Content (absolute)"  = DESeq set-average raw log2FC per pathway.
#   RIGHT "Priority (mitoPPS)"   = the relative mitoPPS Myc effect per pathway.
# The headline is the DISCORDANCE: Myc raises content almost everywhere, yet
# priority is reshuffled -- within OXPHOS the structural SUBUNITS are promoted
# while the ASSEMBLY factors (and the mtDNA arm) are DEMOTED. That subunit-over-
# assembly reallocation is the "OXPHOS exception", visible only at all-pathways
# granularity.
#
# Genotype (Myc+ vs WT within a timepoint) is the CLEAN axis; the ratio cancels the
# per-sample common mode (mitoPPS ambient ~0.42, script 38). Two genotype contrasts
# (6W, 12W); the batch-confounded time contrasts live in the survey figures.
# DESCRIPTIVE / EXPLORATORY: few pathways clear padj<0.05 individually -- read the
# PATTERN (the colour flip between the two blocks), not single tiles.
#
# Reads (read-only; NO analysis re-run -- mitopps_scores was regenerated by the
#   author's post-reconciliation re-run):
#   results/mitopps_scores.rds        -- $mitopps_pairwise (relative diff/padj),
#       $gene_to_pathway (pathway -> gene, current symbols), $pathway_tier1_map.
#   results/interaction_results.rds   -- raw DESeqResults for the absolute ruler.
#   functions/reconcile_gene_symbols.R -- map pathway genes -> Ensembl (recovers
#       renamed genes, e.g. ATP synthase / Complex V).
# =============================================================================

source(here::here("figures", "theme_myc.R"))
source(here::here("functions", "reconcile_gene_symbols.R"))
if (!requireNamespace("patchwork", quietly = TRUE)) {
  stop("fig02 needs patchwork to place the content and priority blocks side by side")
}
if (!requireNamespace("DESeq2", quietly = TRUE)) {
  stop("fig02 needs DESeq2 to coerce the DESeqResults in interaction_results.rds")
}

out_dir <- here::here("outputs", "figures")

mp <- readRDS(here::here("results", "mitopps_scores.rds"))
ir <- readRDS(here::here("results", "interaction_results.rds"))

# --- the two genotype contrasts, both rulers ---------------------------------
#   relative (mitoPPS): mp$mitopps_pairwise contrast names.
#   absolute (DESeq set-LFC): the interaction_results raw DESeqResults.
rel_name <- c("6W" = "Myc_effect_6W", "12W" = "Myc_effect_12W")
abs_res  <- list("6W" = ir$myc_6W_raw, "12W" = ir$myc_12W_raw)
lfc_of   <- function(res) { d <- as.data.frame(res)
  stats::setNames(d$log2FoldChange, rownames(d)) }
abs_lfc  <- lapply(abs_res, lfc_of)

# --- pathways: anchor on the relative ruler; attach tier ----------------------
pw_all <- intersect(unique(mp$mitopps_pairwise$pathway), names(mp$pathway_tier1_map))
tier   <- mp$pathway_tier1_map[pw_all]
gp     <- mp$gene_to_pathway
gcol   <- names(gp)[2]; pcol <- names(gp)[1]      # (Pathway, Gene)

# --- absolute ruler: DESeq set-average raw LFC + one-sample t vs 0 ------------
abs_tbl <- do.call(rbind, lapply(pw_all, function(pw) {
  genes <- unique(gp[[gcol]][gp[[pcol]] == pw])
  do.call(rbind, lapply(names(abs_lfc), function(tp) {
    L <- abs_lfc[[tp]]
    e <- recon_to_ensembl(genes, names(L))
    v <- L[e]; v <- v[is.finite(v)]
    p <- if (length(v) >= 2) suppressWarnings(stats::t.test(v, mu = 0)$p.value) else NA_real_
    data.frame(pathway = pw, tp = tp, ruler = "abs",
               value = if (length(v)) mean(v) else NA_real_, p = p,
               stringsAsFactors = FALSE)
  }))
}))
# BH within each contrast for the absolute ruler
abs_tbl <- do.call(rbind, lapply(split(abs_tbl, abs_tbl$tp), function(d) {
  d$padj <- stats::p.adjust(d$p, "BH"); d }))

# --- relative ruler: mitoPPS pairwise diff + padj ----------------------------
rel_tbl <- do.call(rbind, lapply(names(rel_name), function(tp) {
  r <- mp$mitopps_pairwise[mp$mitopps_pairwise$contrast == rel_name[[tp]], ]
  r <- r[match(pw_all, r$pathway), ]
  data.frame(pathway = pw_all, tp = tp, ruler = "rel",
             value = r$diff, p = r$p_value, padj = r$padj, stringsAsFactors = FALSE)
}))

dat <- rbind(abs_tbl[, c("pathway","tp","ruler","value","padj")],
             rel_tbl[, c("pathway","tp","ruler","value","padj")])
dat$tp   <- factor(dat$tp, levels = c("6W", "12W"), labels = c("Myc @6W", "Myc @12W"))
dat$star <- ifelse(!is.na(dat$padj) & dat$padj < 0.05, "*", "")

# --- ordering: tiers in a fixed order; within tier by relative 6W ------------
tier_lv <- c("OXPHOS", "Mitochondrial central dogma",
             "Protein import, sorting and homeostasis",
             "Mitochondrial dynamics and surveillance",
             "Metabolism", "Signaling", "Small molecule transport")
tier_lab <- c("OXPHOS", "Central dogma", "Import /\nhomeostasis",
              "Dynamics &\nsurveillance", "Metabolism", "Signaling", "SM transport")
names(tier_lab) <- tier_lv
ord_key <- rel_tbl$value[rel_tbl$tp == "6W"][match(pw_all, rel_tbl$pathway[rel_tbl$tp == "6W"])]
pw_order <- pw_all[order(match(tier, tier_lv), ord_key, na.last = TRUE)]

mk <- function(d) {
  d$pathway <- factor(d$pathway, levels = rev(pw_order))          # top = first
  d$tier    <- factor(unname(mp$pathway_tier1_map[as.character(d$pathway)]),
                      levels = tier_lv, labels = tier_lab[tier_lv])
  d
}
d_abs <- mk(dat[dat$ruler == "abs", ])
d_rel <- mk(dat[dat$ruler == "rel", ])

# --- the two blocks ----------------------------------------------------------
LIM_A <- 0.7; LIM_R <- 0.3
heat <- function(d, lim, legend_name, show_y) {
  d$fillv <- pmax(pmin(d$value, lim), -lim)
  ggplot2::ggplot(d, ggplot2::aes(tp, pathway, fill = fillv)) +
    ggplot2::geom_tile(colour = "white", linewidth = 0.4) +
    ggplot2::geom_text(ggplot2::aes(label = star), size = 2.4, colour = "grey10",
                       vjust = 0.78) +
    ggplot2::facet_grid(tier ~ ., scales = "free_y", space = "free_y") +
    ggplot2::scale_fill_gradient2(
      low = "#2166AC", mid = "white", high = "#B2182B", midpoint = 0,
      limits = c(-lim, lim), na.value = "grey88", name = legend_name,
      breaks = c(-lim, 0, lim), labels = c(paste0("<=-", lim), "0", paste0(">=", lim))) +
    ggplot2::scale_x_discrete(position = "top", expand = ggplot2::expansion(0)) +
    ggplot2::labs(x = NULL, y = NULL) +
    theme_myc(base_size = 7) +
    ggplot2::theme(
      axis.line       = ggplot2::element_blank(),
      axis.ticks      = ggplot2::element_blank(),
      axis.text.x.top = ggplot2::element_text(face = "bold", size = 7),
      axis.text.y     = if (show_y) ggplot2::element_text(size = 4.4) else ggplot2::element_blank(),
      panel.spacing.y = ggplot2::unit(1.2, "pt"),
      strip.text.y = if (show_y) ggplot2::element_blank() else
        ggplot2::element_text(angle = 0, size = 6.5, face = "bold", hjust = 0),
      legend.position = "bottom",
      legend.key.height = ggplot2::unit(3, "mm"),
      legend.key.width  = ggplot2::unit(5, "mm"),
      legend.title    = ggplot2::element_text(size = 6.5),
      plot.subtitle   = ggplot2::element_text(face = "bold", size = 8.5, hjust = 0.5))
}

p_abs <- heat(d_abs, LIM_A, "content\nlog2FC", show_y = TRUE) +
  ggplot2::labs(subtitle = "Content (absolute)")
p_rel <- heat(d_rel, LIM_R, "priority\nmitoPPS", show_y = FALSE) +
  ggplot2::labs(subtitle = "Priority (mitoPPS)")

p <- patchwork::wrap_plots(p_abs, p_rel, nrow = 1, widths = c(1.55, 1)) +
  patchwork::plot_annotation(
    title = "Myc raises content broadly but reallocates priority: OXPHOS subunits up, assembly down",
    caption = paste(
      "Left: DESeq set-average raw log2FC (* = one-sample t vs 0, BH<0.05). Right: relative mitoPPS Myc effect (* = padj<0.05).",
      "mitoPPS (Monzel 2025) is content-blind = relative reallocation; genotype is the clean axis. Descriptive/exploratory (n=6/group) -- read the pattern (the colour flip), not single tiles.",
      sep = "\n"),
    theme = ggplot2::theme(
      plot.title   = ggplot2::element_text(face = "bold", size = 10),
      plot.caption = ggplot2::element_text(size = 6, hjust = 0, colour = "grey30",
                                           lineheight = 1.1)))

# Guard: sourced only to obtain `p` (e.g. Quarto) when myc.fig.nosave = TRUE.
if (!isTRUE(getOption("myc.fig.nosave"))) {
  if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)
  save_panel(p, file.path(out_dir, "fig02_reallocation_two_rulers.pdf"),
             width = fig_w[["double"]], height = 285)
}

# =============================================================================
# SANDBOX -- run line-by-line in Positron; skipped by source()
# =============================================================================
if (FALSE) {
  cat("pathways:", length(pw_all), " tiers:", length(unique(tier)), "\n")
  ox <- pw_all[tier == "OXPHOS"]
  chk <- merge(
    reshape(abs_tbl[abs_tbl$pathway %in% ox, c("pathway","tp","value")],
            idvar = "pathway", timevar = "tp", direction = "wide"),
    reshape(rel_tbl[rel_tbl$pathway %in% ox, c("pathway","tp","value")],
            idvar = "pathway", timevar = "tp", direction = "wide"), by = "pathway")
  print(chk[order(chk$value.6W.y), ], row.names = FALSE, digits = 2)
  print(p)
}
