# =============================================================================
# figS4_reallocation_full.R -- "Myc reprioritises the compartment" (full, labelled)
# -----------------------------------------------------------------------------
# The SUPPLEMENTARY, fully-labelled companion to the compact main panel
# (fig02b_reallocation_ranked.R). An ORDERED DOT CHART: every MitoPathway ranked
# by its Myc mitoPPS effect (Myc+ minus WT), most DEMOTED at the bottom -> most
# PROMOTED at the top. mitoPPS (Monzel 2025) is content-blind (each pathway
# ratio-normalized to 1), so the effect is a pure RELATIVE-priority shift. The
# point: reprioritisation is real and STRUCTURED -- the tier colours cluster, with
# biogenesis machinery (import/homeostasis, central dogma) at the promoted top and
# dynamics/surveillance, apoptosis, signalling, transport at the demoted bottom;
# OXPHOS/metabolism sit near zero at the whole-pathway level (their action is the
# within-OXPHOS subunit-vs-assembly split -- supplementary figS3).
#
# One dot per pathway; 6W (filled) and 12W (open) on the SAME panel, joined by a
# thin line (the 6W->12W attenuation). Genotype (Myc+ vs WT within a timepoint) is
# the clean axis. DESCRIPTIVE / EXPLORATORY (n=6/group): the claim is the ordered,
# tier-coherent pattern, not any single pathway.
#
# Reads (read-only; NO re-run -- mitoPPS regenerated by the author's post-
#   reconciliation run):
#   results/mitopps_scores.rds -- $mitopps_pairwise (per pathway x contrast: diff,
#       padj; contrasts Myc_effect_6W / Myc_effect_12W), $pathway_tier1_map.
# =============================================================================

source(here::here("figures", "theme_myc.R"))

out_dir <- here::here("outputs", "figures")

mp   <- readRDS(here::here("results", "mitopps_scores.rds"))
pw   <- mp$mitopps_pairwise
tier <- mp$pathway_tier1_map

# --- per-pathway Myc mitoPPS effect at 6W and 12W ----------------------------
e6  <- pw[pw$contrast == "Myc_effect_6W",  c("pathway", "diff", "padj")]
e12 <- pw[pw$contrast == "Myc_effect_12W", c("pathway", "diff", "padj")]
names(e6)[2:3]  <- c("eff_6W", "padj_6W")
names(e12)[2:3] <- c("eff_12W", "padj_12W")
d <- merge(e6, e12, by = "pathway")
d$tier <- unname(tier[d$pathway])
d <- d[!is.na(d$tier) & !is.na(d$eff_6W), ]

# --- tier labels + palette (Metabolism greyed: neutral bulk) -----------------
tier_lv  <- c("Protein import, sorting and homeostasis", "Mitochondrial central dogma",
              "OXPHOS", "Metabolism", "Signaling",
              "Mitochondrial dynamics and surveillance", "Small molecule transport")
tier_lab <- c("Import / homeostasis", "Central dogma", "OXPHOS", "Metabolism",
              "Signaling", "Dynamics & surveillance", "SM transport")
names(tier_lab) <- tier_lv
tier_col <- c("Import / homeostasis"    = "#D55E00", "Central dogma" = "#E69F00",
              "OXPHOS"                  = "#009E73", "Metabolism"    = "grey72",
              "Signaling"               = "#56B4E9",
              "Dynamics & surveillance" = "#0072B2", "SM transport"  = "#CC79A7")
d$tier <- factor(unname(tier_lab[d$tier]), levels = unname(tier_lab[tier_lv]))

# --- order pathways by the 6W effect (demoted bottom -> promoted top) ---------
d <- d[order(d$eff_6W), ]
d$pathway <- factor(d$pathway, levels = d$pathway)

# long: one row per (pathway, timepoint)
long <- rbind(
  data.frame(pathway = d$pathway, tier = d$tier, tp = "6W",  eff = d$eff_6W,  padj = d$padj_6W),
  data.frame(pathway = d$pathway, tier = d$tier, tp = "12W", eff = d$eff_12W, padj = d$padj_12W))
long$tp <- factor(long$tp, levels = c("6W", "12W"))

p <- ggplot2::ggplot(long, ggplot2::aes(eff, pathway)) +
  ggplot2::geom_vline(xintercept = 0, linewidth = 0.3, colour = "grey55") +
  # thin 6W->12W connector (the attenuation)
  ggplot2::geom_line(ggplot2::aes(group = pathway), colour = "grey78", linewidth = 0.25) +
  ggplot2::geom_point(ggplot2::aes(colour = tier, shape = tp, size = tp)) +
  ggplot2::scale_colour_manual(values = tier_col, name = "MitoPathway tier") +
  ggplot2::scale_shape_manual(values = c("6W" = 16, "12W" = 1), name = "timepoint") +
  ggplot2::scale_size_manual(values = c("6W" = 1.5, "12W" = 1.5), guide = "none") +
  ggplot2::labs(
    x = "Myc mitoPPS effect  (Myc+ - WT, relative priority)", y = NULL,
    title = "Myc reprioritises the mitochondrial compartment",
    subtitle = "MitoPathways ranked by Myc mitoPPS effect (Myc+ - WT): reprioritisation is structured by pathway function (colour).",
    caption = paste(
      "mitoPPS (Monzel 2025), content-blind: each MitoPathway ratio-normalized to 1, so the effect is a pure relative-priority shift.",
      "Filled = 6W, open = 12W (line = the 6W->12W change). Genotype is the clean axis. Descriptive/exploratory (n=6/group).",
      sep = "\n")) +
  theme_myc(base_size = 8) +
  ggplot2::theme(
    axis.text.y     = ggplot2::element_text(size = 4.2),
    axis.ticks.y    = ggplot2::element_blank(),
    panel.grid.major.y = ggplot2::element_line(colour = "grey95", linewidth = 0.2),
    legend.position = "right",
    legend.key.size = ggplot2::unit(3.5, "mm"),
    legend.title    = ggplot2::element_text(size = 7)) +
  ggplot2::guides(
    colour = ggplot2::guide_legend(order = 1, override.aes = list(size = 2.6, shape = 16)),
    shape  = ggplot2::guide_legend(order = 2, override.aes = list(size = 2.2)))

# Guard: sourced only to obtain `p` (e.g. Quarto) when myc.fig.nosave = TRUE.
if (!isTRUE(getOption("myc.fig.nosave"))) {
  if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)
  save_panel(p, file.path(out_dir, "figS4_reallocation_full.pdf"),
             width = fig_w[["double"]], height = 265)
}

# =============================================================================
# SANDBOX -- run line-by-line in Positron; skipped by source()
# =============================================================================
if (FALSE) {
  cat("pathways:", nrow(d), "\n")
  print(head(d[, c("pathway", "eff_6W", "eff_12W", "tier")], 8), digits = 2)   # most demoted
  print(tail(d[, c("pathway", "eff_6W", "eff_12W", "tier")], 8), digits = 2)   # most promoted
  print(p)
}
